
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('identities').del()
    .then(function () {
      // Inserts seed entries
      return knex('identities').insert([
        {id: 1, image1:'images/lbgt.jpg', title:'LGBTQIA+', header:'The Ministry of Health found that the community members have a higher lifetime risk for mental health problems including depression, anxiety, suicide and self-harm, substance misuse and eating disorders.', blurb:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", text_extra:''},
        {id: 2, image1:'images/youngpeople.jpg', title:'Young People', header:'In the last five years,the number of youth (age 15-24) who report struggling with mental health distress has more than doubled.', blurb:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", text_extra:'New Zealand youth have the highest suicide rate in the developed world.'},
        {id: 3, image1:'images/maorisad.jpg', title:'Māori', header:'Māori populations often have limited access to public health, with some of the highest rates of psychological distress and suicide among any ethnicity in New Zealand.', blurb:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", text_extra:''},
        {id: 4, image1:'images/women1.jpg', title:'Women', header:'2016 saw the highest rates of suicide for Kiwi women ever recorded.', blurb:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", text_extra:''},
        {id: 5, image1:'images/oldperson.jpg', title:'The Elderly', header:'Late life suicides have an alarmingly high rate in New Zealand.', blurb:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", text_extra:''},
        {id: 6, image1:'images/RealMen1.jpg', title:'Men', header:'One in eight Kiwi men will experience a depression severe enough to require clinical treatment. If left untreated, men are more likely to develop substance abuse problems while trying to "man up" and face it alone. There is another way.', blurb:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", text_extra:''}
      ]);
    });
};
