
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('identities').del()
    .then(function () {
      // Inserts seed entries
      return knex('identities').insert([
        {id: 1, image1:'images/lbgt.jpg', title:'LGBTQIA+', header:'The Ministry of Health found that the', subheader:' community members have a higher lifetime risk',preblurb:' for mental health problems including depression, anxiety, suicide and self-harm, substance misuse and eating disorders.',blurb:"Across the world, even in 2018, being part of the rainbow family is grounds for discrimination. From microaggressions, homophobia and transphobia, to institutional criminalisation of these lifestyles and behaviors, the struggle for human rights in the LGBTQIA2+ community is far from over. While it may be a long road ahead, there’s heaps we can do to support our Rainbow siblings across Aotearoa and the world. From encouraging harm reduction models to de-stigmatising queer experience, getting better funding for queer mental health providers and education on the specific challenges of LGBTQIA2+ experiences, we’ll be well on our way to a brighter future for mental health across the Rainbow family. ", text_extra:''},
        {id: 2, image1:'images/young1.jpg', title:'Young People', header:'In the last five years,the number of youth (age 15-24) who report struggling with mental health distress has ',subheader:'more than doubled.', blurb:"The Internet has dramatically changed the social landscape, and it’s hit especially hard for young people. With the advent of social media and cyberbullying, today’s youth are in dire need of alternate avenues to mental health support. More and more social contact is created in the digital sphere, meaning less and less time in-person. When bullying is normalised, empathy is at best set aside and at worse, demonised. We all know the challenges of adolescence, and young people today have more barriers to wellbeing than ever. At the same time, the Internet can be an incredible resource for younger folks. To come together, share stories, access new information, and gain support where they might not be getting it yet. With Kiwi youth’s astronomically high rate of suicide, it’s clear we have to do better-- for the next generation, and our own.", text_extra:'New Zealand youth have the',text_extra2:'highest suicide rate in the developed world.'},
        {id: 3, image1:'images/maorisad.jpg', title:'Māori', header:'Māori populations often have limited access to public health, with some of',subheader:' the highest rates of psychological distress and suicide',preblurb:'among any ethnicity in New Zealand.', blurb:"With the dissemination of Maori young people coming into cities, the loss of cohesion on the Maree has impacted communities greatly. For many, the bonds have drifted apart and the strength of tight-knit connections have been weakened. Coming of age today in an individualistic society has harmed the unity of many Maori communities, and the fight to “go back” to the way things were proves a heated debate for the modern world. One thing we can do to nurture and sustain the connectedness being threatened by individualism is to find new ways to address Maori mental health. Log on to the forum to find resources, share experiences, and sustain the storytelling traditions that guide our communities. Gather with your aunties and cousins online, and together we’ll find a way.", text_extra:''},
        {id: 4, image1:'images/women1.jpg', title:'Women', header:'2016 saw the highest rates of suicide for Kiwi women', subheader:' ever recorded.',blurb:"Many women have a common experience of feeling like the emotional caretaker of others. Mothers, sisters, wives … even as employees, friends, and colleagues, women are frequently expected to pick up the emotional slack in any given situation. This dynamic often means that, if a woman doesn’t require mental health support for herself, at some point in her life she will likely be asked to tend to the mental health of someone else. Whatever the context -- perhaps depression, the impacts of addiction, or domestic violence -- it’s imperative that women come together to share their experience, strength, hope, and tools for approaching mental illness.", text_extra:''},
        {id: 5, image1:'images/oldperson.jpg', title:'The Elderly', subheader:'Late life suicides', preblurb:' have an alarmingly high rate in New Zealand.', blurb:"For many cultures, it’s normal for families to live in an intergenerational household, with  grandparents, parents, and grandkids all living under one roof. Unfortunately, this type of togetherness is less and less the norm. For our elders, this separation often produces isolation and loneliness. The later parts of our lives can, and should, be full of meaning, purpose and joy. Let’s talk about nourishing the mental health of our elders, and how we can support them and enjoy their wisdom while we still can!", text_extra:''},
        {id: 6, image1:'images/RealMen1.jpg', title:'Men', header:'One in eight Kiwi men will experience a depression severe enough to require clinical treatment. If left untreated, men are more likely to develop substance abuse problems while trying to "man up" and face it alone.',subheader:'There is another way.', blurb:"The traditional Kiwi bloke is a staunch character, who learned early to be tough and “man up” wherever emotions are involved. But this image of manhood has proven destructive for all of us-- from emotionally absent fathers, to husbands with anger management problems, to boys that simply don’t know how to deal with their feelings and resort to violence to solve their discomfort. What we need as men is what our families need, and it’s what New Zealand needs -- a healthier version of masculinity, and an end to the toxic violence these stereotypes perpetuate. Men today are already leading a new way forward in creating a space where masculinity and strength are synonymous with emotional awareness, communication skills, and even vulnerability. For more information on this movement, check out our friends at Tough Talk, where psychologist Sam O'Sullivan explores strength and vulnerability with Kiwi blokes around Aotearoa.", text_extra:''}
      ]);
    });
};
